const colors = {
  WHITE: '#FFF',

  PRIMARY_HIGHLIGHT: '#FE3E6D',

  PRIMARY_GRAY: '#3B3B3B',
  PRIMARY_GRAY_DARKEN: '#6B7076',
  PRIMARY_GRAY_LIGHTEN: '#F0F4F8',
  SECONDARY_GRAY_LIGHTEN: '#DEE4E9',

  SECONDARY_BLUE: '#1A93DA',
  SECONDARY_BLUE_LIGHTEN: '#EAF7FF'
}

export default colors
